#!/usr/bin/env sh

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$HOME/.config/sketchybar/icons.sh"
source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"


##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=30	\
	blur_radius=50			\
	position=bottom			\
	sticky=off				\
	padding_left=0			\
	padding_right=0			\
	y_offset=0				\
	margin=0				\
	notch_width=0			\
	color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="Hack Nerd Font:Bold:16.0"	\
	padding_right=0                       					\
	padding_left=0											\
															\
	label.font="Menlo:Bold:16.0"					\
	label.color=$WHITE										\
															\
	label.padding_left=0                  					\
	label.padding_right=0                 					\
															\
	icon.color=$WHITE										\
	icon.padding_left=0                   					\
	icon.padding_right=0

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

# source "$ITEM_DIR/apple.sh"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

# for i in "${!SPACE_ICONS[@]}"
# do
# 	sid=$(($i+1))
# 	sketchybar --add space space.$sid left			\
# 		--set space.$sid associated_space=$sid      \
# 		icon=${SPACE_ICONS[i]}						\
# 		background.color=0x44ffffff					\
# 		background.corner_radius=0					\
# 		background.height=30						\
# 		background.drawing=off						\
# 		label.drawing=off							\
# 		script="$PLUGIN_DIR/space.sh"				\
# 		click_script="yabai -m space --focus $sid"
# 	done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set


# sketchybar -m --add event window_focus \
# 	--add title_change
#
# sketchybar -m --add item title left						\
# 	--set title script="$PLUGIN_DIR/window_title.sh"	\
# 	icon=">"											\
# 	icon.padding_left=10								\
# 														\
# 	background.color=$BLACK								\
# 	background.height=30								\
# 														\
# 	label.padding_left=10								\
# 	label.padding_right=10								\
# 	label.color=$GREEN									\
# 														\
# 	--subscribe title window_focus front_app_switched space_change title_change



sketchybar \
	--add item front_app left               \
	--set front_app							\
	icon=">"								\
	icon.padding_left=10					\
	background.color=$BLACK					\
	label.padding_left=10					\
	background.height=30					\
	label.padding_right=10					\
	script="$PLUGIN_DIR/front_app.sh"		\
	label.color=$GREEN						\
	--subscribe front_app front_app_switched 


##### Adding middle Items #####


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source "$ITEM_DIR/clock.sh"

sketchybar --add item  ip_address right                              \
           --set       ip_address script="$PLUGIN_DIR/ip_address.sh" \
                                  update_freq=30                     \
                                  padding_left=2                     \
                                  background.height=30               \
								  icon.padding_left=5\
								  icon.padding_right=5\
								  label.padding_right=10\
								  icon.highlight=on\
								  icon.highlight_color=$BLACK\
								  label.highlight=on\
								  label.highlight_color=$BLACK\
           --subscribe ip_address wifi_change                        \
                                                                     \
           --add item  volume right                                  \
           --set       volume script="$PLUGIN_DIR/volume.sh"         \
                              background.height=30                   \
							  label.padding_right=10\
							  icon.padding_left=10\
							  icon.padding_right=5\
           --subscribe volume volume_change                          \
                                                                     \
           --add item  battery right                                 \
           --set       battery script="$PLUGIN_DIR/battery.sh"       \
                               update_freq=120                       \
                               icon.padding_left=8                        \
							   icon.padding_right=5\
							   label.padding_right=10\
							   icon.color=$GREEN\
                               background.border_width=0             \
                               background.height=24                  \
           --subscribe battery system_woke power_source_change

# Bracket

# sketchybar --add bracket status ip_address volume battery     \
#            --set         status background.color=$BACKGROUND  \
# 								background.height=30\
# 								background.border_width=2 \
#                                 background.border_color=$WHITE

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update


